---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: create vpc
      ec2_vpc_net:
        name: "PvtNetwork"
        state: present
        cidr_block: 192.168.0.0/24
        resource_tags: {"Env":"Dev"}
        region: us-east-1
