
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: create instance ec2
      ec2:
        key_name: my_keypair
        instance_type: t2.micro
        image: ami-009d6802948d06e52
        wait: yes
        count: 1
        vpc_subnet_id: subnet-82c668bc
        assign_public_ip: yes
