---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create new ec2 key
      local_action:
        module: ec2_key
        name: my_key
        key_material: 'ssh-rsa xxxxx'
        state: present
